# Generated by Django 2.2.5 on 2019-10-07 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company_logo', models.URLField()),
                ('company_logo_alt', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=50)),
                ('more_info_link', models.URLField()),
                ('salary', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('first_seen', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
