# Generated by Django 2.2.5 on 2019-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brighterMonday', '0002_auto_20191007_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_logo_alt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
